name: Issue Handling

on:
    issues:
        types: [opened]
jobs:
  comment_and_close:
    name: Comment and close issue
    if: github.repository == 'bitfocus/companion-module-adlerluiz-ytmdesktop'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Hi @${{ github.event.issue.user.login }}! 

            This repository is only used for releasing the package. All development is on a separate repository.

            For issue tracking and active development, please visit the forked repository [here](https://github.com/dandanthedev/companion-module-adlerluiz-ytmdesktop)
      - name: Close issue
        run: gh issue close "$NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}