name: Publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: Makepad-fr/auto-release-on-version-bump-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
